version: '3'

services:
  bot:
    build:
      context: ../
      dockerfile: ./docker/gonstructor/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - gonstructor
networks:
  gonstructor: